### ISSUE TITLE
[Feature Request] - Make the migrations compatible with Docker

### ISSUE THREAD

**Issue by jdaibello** [vania-dart/framework#177]
**Is your feature request related to a problem? Please describe.**
Hi, I really like the framework, but I'm frustrated that the migrations are not compatible with Docker Compose when adding a database service like Postgres, since the database will not be available when running vania migrate as seen in default Dockerfile.

**Comment by javad-zobeidi** [comment]
@jdaibello 

Thanks for the feedback and glad you like the framework! To help resolve the migration issues with Docker Compose and Postgres, please try the following:

Start the Database First: Make sure your Postgres container is fully running and ready

**Comment by javad-zobeidi** [comment]
@jdaibello 

Thanks for the feedback and I'm glad you like the framework! To help resolve the migration issues with Docker Compose and Postgres, please try the following:

Make sure your Postgres container is fully running and ready

check your Vania project container and the Postgres container are on the same Docker network

Double-check the database configuration in your .env file. Ensure that the host, port, username, password, and database name align with your Docker Compose settings



Try this Docker Compose

```yml

version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase

volumes:
  app:
  pgdata:

```

**Comment by jdaibello** [comment]
> [@jdaibello](https://github.com/jdaibello)
> 
> Thanks for the feedback and I'm glad you like the framework! To help resolve the migration issues with Docker Compose and Postgres, please try the following:
> 
> Make sure your Postgres container is fully running and ready
> 
> check your Vania project container and the Postgres container are on the same Docker network
> 
> Double-check the database configuration in your .env file. Ensure that the host, port, username, password, and database name align with your Docker Compose settings
> 
> Try this Docker Compose
> 
> version: '3.9'
> 
> services:
>   postgres:
>     image: postgres:13-alpine
>     container_name: postgres
>     restart: always
>     environment:
>       POSTGRES_USER: myuser
>       POSTGRES_PASSWORD: mypassword
>       POSTGRES_DB: mydatabase
>     volumes:
>       - pgdata:/var/lib/postgresql/data
>     ports:
>       - "5432:5432"
> 
>   vania:
>     build: .
>     image: vania/app:latest
>     container_name: vania
>     restart: always
>     depends_on:
>       - postgres
>     volumes:
>       - .:/app
>     ports:
>       - "8000:8000"
>     environment:
>       - DB_HOST=postgres
>       - DB_PORT=5432
>       - DB_USER=myuser
>       - DB_PASSWORD=mypassword
>       - DB_NAME=mydatabase
> 
> volumes:
>   app:
>   pgdata:

Hi @javad-zobeidi.

I just updated my docker-compose using this template, but Vania is still unable to run to migrations, because the migrations are running on build time, but the database start running on runtime. You can see the screenshot below, which shows no tables, but shows that the app is connected to the database.

![Image](https://github.com/user-attachments/assets/59d53966-4652-4d36-aeea-977396f2e4f3)

**Comment by javad-zobeidi** [comment]
Open DockerFile find and remove this line `RUN vania migrate`

Then add `command` to your docker-compose file

```
    command: >
      sh -c "vania migrate"
```


```yml
version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    command: >
      sh -c "vania migrate"

volumes:
  app:
  pgdata:
```
